import React from 'react';

import { Metadata } from 'next';

import { Dashboard } from '@/components/dashboard/Dashboard';
import Footer from '@/components/shared/footer/Footer';

export const metadata: Metadata = {
  title: " Saiful | Blogs",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode}) => {
  return (
    <div>
      <Dashboard>
        {children}
      </Dashboard>
        <Footer/>

    </div>
  );
};

export default DashboardLayout;
