import React from 'react'
import BlogDetailsCard from '../../components/BlogDetailsCard'
import { Metadata } from 'next'
type TProps={
    params:{
        blogId:string
    }
}
export const metadata: Metadata = {
  title: " Saiful | Blogs | Details",
  description: "Generated by portfolio blog",
};
const BlogDetailsPage = ({params}:TProps) => {
  const blogId=params.blogId
  return (
    <div>
      <BlogDetailsCard blogId={blogId} />
    </div>
  )
}

export default BlogDetailsPage