import React from 'react';

import { Metadata } from 'next';

import { Dashboard } from '@/components/dashboard/Dashboard';
import Footer from '@/components/shared/footer/Footer';
import { AdminDashboard } from '@/components/adminDashboard/AdminDashboard';

export const metadata: Metadata = {
  title: " Saiful | Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: { children: React.ReactNode}) => {
  return (
    <div>
      <AdminDashboard>
        {children}
      </AdminDashboard>
        <Footer/>

    </div>
  );
};

export default DashboardLayout;
